# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: NZTC Challenge
short_description: Pathways to net zero
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Best agents
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: True
start_date: 2021-01-01 00:00:00
end_date: 2022-02-01 00:00:00
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Average Cost"],
        "default_order_by": "Average Cost",
      }
  - id: 2
    schema:
      {
        "labels": ["Average Cost"],
        "default_order_by": "Average Cost",
      }
  - id: 3
    schema:
      {
        "labels": ["Average Cost"],
        "default_order_by": "Average Cost",
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-01-01 00:00:00
    end_date: 2022-02-01 00:00:00
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
  - id: 2
    name: Open-loop Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-01-01 00:00:00
    end_date: 2022-02-01 00:00:00
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: open
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
  - id: 3
    name: Closed-loop Phase
    description: templates/challenge_phase_3_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-01-01 00:00:00
    end_date: 2022-02-01 00:00:00
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: closed
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False
  - challenge_phase_id: 3
    leaderboard_id: 3
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False